#!/bin/bash

#author: Danniella Kitio
#date: february 2023
   ##---- docker installation on ubuntu and centos7

#first clean up the system
sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine

#secondary setup the docker repository
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

#thirtly  install the docker engine
 sudo yum install docker-ce docker-ce-cli containerd.io
 # And finaly check the status,start and enable docker daemon
  sudo systemctl status docker
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl status docker